MODEL:
  NAME: Yolo3
  LOAD: ./pretrained/darknet53.conv.74
DATA:
  DATASET: voc
  TRANSFORM: yolo3
  SCALE: 448
OPTIMIZE:
  OPTIMIZER: sgd
  BASE_LR: 0.00005
  SCHEDULER: 5x
  BATCH_SIZE: 18
TEST:
  NMS_THRESH : 0.5  # nms iou thresh at test time
  CONF_THRESH: 0.05 # confidence thresh to keep at test time
MISC:
  VAL_FREQ: 50
  SAVE_FREQ: 1
  NUM_WORKERS: 0